environment:
  name: staging
  namespace: staging-apps
  cluster: in-cluster
  
  defaults:
    replicas: 2
    
    image:
      pullPolicy: IfNotPresent
    
    resources:
      requests:
        cpu: 250m
        memory: 256Mi
      limits:
        cpu: 1000m
        memory: 1Gi
    
    ingress:
      className: nginx
      tls:
        enabled: true
    
    monitoring:
      enabled: true
    
    autoscaling:
      enabled: false
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  
  metadata:
    labels:
      environment: staging
      cost-center: engineering
      monitoring: enabled
      istio-injection: enabled
    annotations:
      description: "Staging environment for pre-production validation"
