# Values need to be scoped under the chart dependency name
demo-app:
  replicaCount: 1

  volume:
    enabled: false
    server: ""
    path: ""
    mountPath: ""

  image:
    repository: nginx
    pullPolicy: IfNotPresent
    tag: "1.0.0"

  imagePullSecrets: []

  nameOverride: ""
  fullnameOverride: ""

  serviceAccount:
    create: true
    annotations: {}
    name: ""

  tls:
    enabled: false

  podAnnotations: {}

  podSecurityContext: {}

  envVar:
    - name: APP_ENV
      value: dev
    - name: LOG_FORMAT
      value: json

  securityContext: {}

  service:
    type: ClusterIP
    port: 8080
    targetPort: 8080

  route:
    enabled: false
    annotations:
      haproxy.router.openshift.io/timeout: 120s

  customRoute:
    enabled: false
    routes: []

  ingress:
    enabled: false
    annotations: {}
    hosts:
      - host: chart-example.local
        paths:
          - path: /
            backend:
              serviceName: chart-example.local
              servicePort: 80
    tls: []

  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80

  nodeSelector: {}

  tolerations: []

  affinity: {}
