# Common values for all environments
replicaCount: 1

volume:
  enabled: false
  server: ""
  path: ""
  mountPath: ""

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: latest

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

tls:
  enabled: false

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

envVar:
  - name: APP_ENV
    value: staging
  - name: LOG_FORMAT
    value: json

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

route:
  enabled: false
  annotations:
    haproxy.router.openshift.io/timeout: 120s

customRoute:
  enabled: false
  routes: []

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          backend:
            serviceName: chart-example.local
            servicePort: 80
  tls: []

resources:
  limits:
    cpu: 1000m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
