apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
spec:
  description: Platform infrastructure components
  
  sourceRepos:
    - 'git@github.com:Tiriyon/isrc-demo-app-catalog.git'
    - 'git@github.com:Tiriyon/isrc-demo-platform-control.git'
  
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
